### ISSUE TITLE
Pokemon rewards

### ISSUE THREAD

**Issue by aggarcia42** [mid-kid/pmdrtdx_passwords#1]
Hi mate, have to ask something i was about to start a project just like this cause cause i got interested in the pokemon code/decode.

Seen your web you have 4 choices in Reward
0 - None
1- Regular
2- Special
3- Deluxe
(and well MAX that you did not add i think)
Have to ask if there is anyway i can change the values to get the item/s, experience, and points that i want to as reward
I tried to find it but my Python skills are not that good

**Comment by mid-kid** [comment]
Sorry for the late response.

The reward value consists of two bits, which can only represent four different values. Are you sure MAX isn't just Deluxe?

**Comment by aggarcia42** [comment]
Yeah no worries
I had seen how it worked yeah MAX is like a Deluxe in game thing.
And yeah i think the are constant values depending you choose one of the 4 options so i have no been able to change it.
Anyways i really loved to see there is someone as crazy as me interested in this pokemon code thing you continue like this thanks mate.
